# Generated by Django 4.0.5 on 2022-07-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Quantity', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('InvoiceNo', models.CharField(max_length=1000)),
                ('Warranty', models.CharField(max_length=1000)),
                ('Price', models.CharField(max_length=1000)),
                ('Department', models.CharField(max_length=1000)),
                ('PurchasingDate', models.CharField(max_length=1000)),
            ],
        ),
    ]
